#!/bin/bash

source "${LIB_DIR}/compiler"

cache="${LIB_DIR}/build/curl-${ARCH}"
rm -rf "${cache}"
mkdir -p "${cache}"

cp -r "${EXT_UNPACK_DIR}/curl" "${cache}"
cd "${cache}/curl"

./configure --prefix="${SYSROOT}" --host="${HOST_COMPILER}" --without-ssl --without-zlib \
--disable-ftp --disable-gopher --disable-file --disable-imap --disable-ldap --disable-ldaps \
--disable-pop3 --disable-proxy --disable-rtsp --disable-smtp --disable-telnet --disable-tftp \
--without-gnutls --without-libidn --without-librtmp --disable-dict --without-smb

make
make install
