#!/bin/bash

source "${LIB_DIR}/compiler"

if [ ${ARCH} == "windows-x86" ]; then
    export AA="mingw"
elif [ ${ARCH} == "windows-x64" ]; then
    export AA="mingw64"
fi

cache="${LIB_DIR}/build/openssl-${ARCH}"
rm -rf "${cache}"
mkdir -p "${cache}"

cp -r "${EXT_UNPACK_DIR}/openssl" "${cache}"
cd "${cache}/openssl"

./Configure --static --prefix="${SYSROOT}" \
--with-zlib-include="${SYSROOT}/include" --with-zlib-lib="${SYSROOT}/lib" \
$AA no-asm no-shared

make
make install
