#!/bin/bash

NERVA_DIR="${ROOT_DIR}/$1"

mkdir -p ${NERVA_DIR}/builder/build/release/translations
cd ${NERVA_DIR}/builder/build/release/translations
cmake ${NERVA_DIR}/translations
make

cd ${NERVA_DIR}/builder
source "${LIB_DIR}/compiler"
export NERVA_BUILD_DISTRO=android
export NERVA_BUILD_DISTRO_VERSION=${NERVA_ARCH}
./android-builder
