#!/bin/bash

source "${LIB_DIR}/compiler"

cache="${LIB_DIR}/build/boost-${ARCH}"
rm -rf "${cache}"
mkdir -p "${cache}"

cp -r "${EXT_UNPACK_DIR}/boost" "${cache}"
cd "${cache}/boost"

./bootstrap.sh

BUILD_DIR="${cache}/output"
PATH="${NDK}/${HOST_COMPILER}/bin:${NDK}/bin:${SYSROOT}/include:${SYSROOT}/lib:$PATH"

./b2 --build-type=minimal address-model=64 variant=release link=static runtime-link=static \
--with-serialization --with-date_time --with-regex --with-program_options --with-filesystem --with-chrono --with-thread \
--build-dir="${BUILD_DIR}" --stagedir="${BUILD_DIR}" \
toolset=clang threading=multi threadapi=pthread target-os=android install --prefix="${SYSROOT}"
