#!/bin/bash

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

files=($(find ${dir}/builds/*.zip))
for item in ${files[*]}
do
  f=$(basename $item)
  scp $item $1:/var/www/html/content/binaries/$f
done
