#!/bin/bash

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source ${dir}/context/src/nerva/builder/helpers
detectversion

rm ${dir}/version.php
verfile=$(sed -e "s/{NERVA_VERSION}/${NERVA_VERSION}/" -e "s/{NERVA_CODENAME}/${NERVA_CODENAME}/" ${dir}/version.php.template)
echo $verfile > ${dir}/version.php
exit 1

files=($(find ${dir}/builds/*.zip))
for item in ${files[*]}
do
  f=$(basename $item)
  md5=($(md5sum $item))
  echo $md5 > ${dir}/builds/$f.md5.txt
  scp $item $1:/var/www/html/content/binaries/$f
done

files=($(find ${dir}/builds/*.md5.txt))
for item in ${files[*]}
do
  f=$(basename $item)
  scp $item $1:/var/www/html/content/binaries/$f
done
