#!/bin/bash

cache="${LIB_DIR}/build/boost-${ARCH}"
rm -rf "${cache}"
mkdir -p "${cache}"

cp -r "${EXT_UNPACK_DIR}/boost" "${cache}"
cd "${cache}/boost"

./bootstrap.sh

BUILD_DIR="${cache}/output"
PATH="${SYSROOT}/include:${SYSROOT}/lib:$PATH"

./b2 --build-type=minimal address-model=64 variant=release link=static runtime-link=static \
--with-serialization --with-date_time --with-regex --with-program_options --with-filesystem --with-chrono --with-thread \
--build-dir="${BUILD_DIR}" --stagedir="${BUILD_DIR}" cflags="-fPIC" cxxflags="-fPIC" \
toolset=gcc threading=multi threadapi=pthread target-os=linux install --prefix="${SYSROOT}"
