#!/bin/bash

source "${LIB_DIR}/compiler"

cache="${LIB_DIR}/build/boost-${ARCH}"
rm -rf "${cache}"
mkdir -p "${cache}"

cp -r "${EXT_UNPACK_DIR}/boost" "${cache}"
cd "${cache}/boost"

echo "using gcc : : ${HOST_COMPILER}-g++ ;" > "${cache}/user-config.jam"

./bootstrap.sh --with-icu="${SYSROOT}"

BUILD_DIR="${cache}/output"
PATH="${SYSROOT}/bin:${SYSROOT}/include:${SYSROOT}/lib:$PATH"

./b2 --build-type=minimal address-model=64 variant=release link=static runtime-link=static \
--user-config="${cache}/user-config.jam" -sICU_PATH=${SYSROOT} \
--with-serialization --with-date_time --with-regex --with-program_options --with-filesystem --with-chrono --with-thread --with-locale \
--build-dir="${BUILD_DIR}" --stagedir="${BUILD_DIR}" cflags="-fPIC" cxxflags="-fPIC" \
toolset=gcc threading=multi threadapi=win32 target-os=windows install --prefix="${SYSROOT}"
