#!/bin/bash

ICU_HOST_BUILD_DIR="${LIB_DIR}/build/icu-x86_64"
ICU_TARGET_BUILD_DIR="${LIB_DIR}/build/icu-${ARCH}"

function host()
{
#    export CFLAGS="-O3 -DU_USING_ICU_NAMESPACE=1 \
#    -DU_HAVE_NL_LANGINFO_CODESET=0 -D__STDC_INT64__ -DU_TIMEZONE=0 \
#    -DUCONFIG_NO_LEGACY_CONVERSION=1 -DUCONFIG_NO_BREAK_ITERATION=1 \
#    -DUCONFIG_NO_COLLATION=0 -DUCONFIG_NO_FORMATTING=0 -DUCONFIG_NO_TRANSLITERATION=0 \
#    -DUCONFIG_NO_REGULAR_EXPRESSIONS=1 -DU_DISABLE_RENAMING=1"
#    export CPPFLAGS=$CFLAGS

    mkdir -p "${ICU_HOST_BUILD_DIR}"
    cd "${ICU_HOST_BUILD_DIR}"

    "${EXT_UNPACK_DIR}/icu/icu4c/source/runConfigureICU" Linux --enable-extras=yes \
    --enable-strict=no --enable-static --enable-shared=no --enable-tests=yes --disable-renaming \
    --enable-samples=no --enable-dyload=no --with-data-packaging=files

    make
}

function target()
{
    source "${ROOT_DIR}/libs/compiler"

#    export COMMONFLAGS="-I${SYSROOT}/include/ \
#    -O3 -DU_USING_ICU_NAMESPACE=1 \
#    -DU_HAVE_NL_LANGINFO_CODESET=0 -DU_TIMEZONE=0 \
#    -DUCONFIG_NO_LEGACY_CONVERSION=1 -DUCONFIG_NO_BREAK_ITERATION=1 \
#    -DUCONFIG_NO_COLLATION=0 -DUCONFIG_NO_FORMATTING=0 -DUCONFIG_NO_TRANSLITERATION=0 \
#    -DUCONFIG_NO_REGULAR_EXPRESSIONS=1 -DU_DISABLE_RENAMING=1"
#    export CFLAGS="${COMMONFLAGS} -std=c11"
#    export CPPFLAGS="${COMMONFLAGS}"

    mkdir -p "${ICU_TARGET_BUILD_DIR}"
    cd "${ICU_TARGET_BUILD_DIR}"

    "${EXT_UNPACK_DIR}/icu/icu4c/source/configure" --with-cross-build="${ICU_HOST_BUILD_DIR}" \
    --enable-extras=yes --enable-strict=no --enable-static=yes --enable-shared=no \
    --enable-tests=no --enable-samples=no --enable-dyload=no --enable-renaming=no \
    --host=${HOST_COMPILER} --prefix="${SYSROOT}" --with-data-packaging=files

    make
    make install
}

host
target
