#!/bin/bash

export AA="linux-x86_64"

cache="${LIB_DIR}/build/openssl-${ARCH}"
rm -rf "${cache}"
mkdir -p "${cache}"

cp -r "${EXT_UNPACK_DIR}/openssl" "${cache}"
cd "${cache}/openssl"

./Configure --static --prefix="${SYSROOT}" -fPIC \
--with-zlib-include="${SYSROOT}/include" --with-zlib-lib="${SYSROOT}/lib" \
$AA no-asm no-shared

make
make install
