#!/bin/bash

cache="${LIB_DIR}/build/libzmq-${ARCH}"
rm -rf "${cache}"
mkdir -p "${cache}"

cp -r "${EXT_UNPACK_DIR}/libzmq" "${cache}"
cd "${cache}/libzmq"

CFLAGS="${CFLAGS} -fPIC" 
CXXFLAGS="${CXXFLAGS} -fPIC" 

./autogen.sh
./configure \
    --without-docs \
    --disable-curve-keygen \
    --enable-libunwind=no \
    --enable-shared=no \
    --enable-static=yes \
    --with-libsodium=yes \
    --prefix="${SYSROOT}"

make
make install
