#!/bin/bash -e

export ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ ! -f "${ROOT_DIR}/env" ]; then
	echo "No configuration found. Please run ./configure"
	exit 1
fi

source ${ROOT_DIR}/env

export DL_CACHE_DIR="${ROOT_DIR}/.dl-cache"
export EXT_PACK_DIR="${ROOT_DIR}/.ext-packed"
export EXT_UNPACK_DIR="${ROOT_DIR}/.ext-unpacked"
export LIB_DIR="${ROOT_DIR}/libs"
export NDK_VER="android-ndk-r17c"
export BOOST_VER_DOT="1.68.0"
export BOOST_VER_US="boost_1_68_0"

export NDK_DL_LINK="https://dl.google.com/android/repository/${NDK_VER}-linux-x86_64.zip"
export BOOST_DL_LINK="https://dl.bintray.com/boostorg/release/${BOOST_VER_DOT}/source/${BOOST_VER_US}.tar.gz"

export NDK="${ROOT_DIR}/ndk-${ARCH}"
export NDK_ROOT="${ROOT_DIR}/${NDK_VER}"
export SYSROOT="${NDK}/sysroot/usr"
export XNV_BIN_DIR="${LIB_DIR}/build/nerva-${ARCH}/bin"

function unpack()
{
	path="${EXT_PACK_DIR}/$1"

	if [ ! -d "${path}" ]; then
		tar xJf ${path}.tar.xz -C ${EXT_UNPACK_DIR}
	fi
}

function init()
{
	cd "${ROOT_DIR}"

	if [ ! -d ${EXT_UNPACK_DIR} ]; then
		mkdir ${EXT_UNPACK_DIR}
	fi

	# Unpack the NDK
	if [ ! -d "${ROOT_DIR}/${NDK_VER}" ]; then	
		unzip -qq "${DL_CACHE_DIR}/${NDK_VER}.zip" -d ${ROOT_DIR}
	fi

	# Unpack Boost
	if [ ! -d "${EXT_UNPACK_DIR}/boost" ]; then	
		tar xzf "${DL_CACHE_DIR}/${BOOST_VER_US}.tar.gz" -C ${EXT_UNPACK_DIR}
		mv "${EXT_UNPACK_DIR}/${BOOST_VER_US}" "${EXT_UNPACK_DIR}/boost"
	fi
	
	unpack "zlib"
	unpack "openssl"
	unpack "libsodium"
	unpack "libzmq"
	unpack "cppzmq"
	unpack "curl"
}

function environment()
{
	init
	
	if [ ! -d "${NDK}" ]; then	
		cd "${ROOT_DIR}"
		"${NDK_ROOT}/build/tools/make_standalone_toolchain.py" --api ${ANDROID_API} \
		--stl=libc++ --arch ${NDK_ARCH} --install-dir "${NDK}"
	fi

	"${LIB_DIR}/build_boost"
	"${LIB_DIR}/build_zlib"
	"${LIB_DIR}/build_ssl"
	"${LIB_DIR}/build_sodium"
	"${LIB_DIR}/build_zmq"

	cp "${EXT_UNPACK_DIR}/cppzmq/zmq.hpp" "${SYSROOT}/include/zmq.hpp"
	cp "${EXT_UNPACK_DIR}/cppzmq/zmq_addon.hpp" "${SYSROOT}/include/zmq_addon.hpp"

	"${LIB_DIR}/build_curl"
	cp -r "${EXT_UNPACK_DIR}/curl/include/curl" "${SYSROOT}/include"
}

function nerva()
{
	"${LIB_DIR}/build_nerva"
}

$1 $2
