#!/bin/bash

NERVA_DIR="${ROOT_DIR}/nerva"

cache="${LIB_DIR}/build/nerva-${ARCH}"
rm -rf "${cache}"
mkdir -p "${cache}/translations"

# Build the translations on host architecture
cd "${cache}/translations"
cmake "${NERVA_DIR}/translations"
make

# Cross compile NERVA for Windows
cd "${cache}"
source "${LIB_DIR}/compiler"

cmake -D BUILD_TESTS=OFF \
-D STATIC=ON -D BUILD_64=ON -D ARCH="armv8-a" -D CMAKE_BUILD_TYPE=release \
-D CMAKE_SYSTEM_NAME="Linux" -D BUILD_SHARED_LIBS=OFF -D BUILD_TAG=${ARCH} "${NERVA_DIR}"
make -j4
